---
title: "final-project"
format: html
editor: visual
---

# Assessing Excess Mortality in Puerto Rico During Hurricane Maria

### Abstract

\[intro sentence\]. Estimates of the death toll now range from 1,400 to nearly 5,000, but months after the hurricane the official death toll reported by the Puerto Rican government remained stubbornly low. This project attempts to statistically analyze Puerto Rico's Department of Health Demographic Registry mortality data from 2002 to 2017 to identify excess mortality during Hurricane Maria. We begin by examining population and mortality trends across age and sex groups, statistically model excess mortality in 2017 during Hurricane Maria as compared to typical mortality rates, and compare our dataset with existing data on hurricane mortality. We identify \[results\]. We finally reflect on the value of rigorous data analysis during natural disasters with particular regard to the political aims of \[something\].

### Introduction

On September 20, 2017, the devastating tropical cyclone Hurricane Maria made landfall on Puerto Rico's southeast coast. Storm surges, flooding, and high winds resulted in landslides, tremendous infrastructural damages, loss of nearly 80% of the country’s agricultural land, and resulted in damage estimated at more than \$90 billion USD. All 3.4 million residents were left without electricity when the island’s power grid was destroyed, resulting in a blackout that was not fully resolved for months after the storm ([here](https://www.nytimes.com/2017/09/21/us/hurricane-maria-puerto-rico.html)). Two weeks after the storm fewer than 10% of residents had regained electrical power, while fewer than half had access to drinking water ([here](https://www.theguardian.com/world/2017/oct/03/puerto-rico-new-death-toll-hurricane-maria-trump-visit)). Morgues reported “overflowing” bodies, unsurprising given the devastation of the storm ([here](https://www.nbcnews.com/storyline/puerto-rico-crisis/puerto-rico-9-months-after-hurricane-maria-questions-persist-over-n883921)). However, the government of Puerto Rico maintained that the death count was merely 64 deaths more than two months after the storm’s initial landfall ([here](https://www.nytimes.com/interactive/2017/12/08/us/puerto-rico-hurricane-maria-death-toll.html)). Media and investigative journalists argued that counts were likely significantly higher, and began mounting lawsuits against the Puerto Rican government with requests for more information on deaths ([here](https://www.cnn.com/2018/06/12/politics/sutter-puerto-rico-records-delay-invs/index.html)). Work by data scientists and investigative journalists at the New York Times, George Washington University, and other organizations suggested that mortality during late 2017 exceeded historical estimates by more than 1,000 deaths ([here](https://www.nytimes.com/interactive/2017/12/08/us/puerto-rico-hurricane-maria-death-toll.html), [here](https://publichealth.gwu.edu/sites/g/files/zaxdzs4586/files/2023-06/acertainment-of-the-estimated-excess-mortality-from-hurricane-maria-in-puerto-rico.pdf)). Ultimately, on August 9, 2018, nearly a year after the storm made its initial descent, the government of Puerto Rico acknowledged that more than 2,000 people died as a result of Hurricane Maria. 

One of the most essential statistical tools used by researchers to determine excess mortality was generalized linear models ([here](https://publichealth.gwu.edu/sites/g/files/zaxdzs4586/files/2023-06/acertainment-of-the-estimated-excess-mortality-from-hurricane-maria-in-puerto-rico.pdf)). Linear models allow statisticians to rigorously assess relationships between two variables while accounting the effects of additional variables that may influence this relationship. These models offer simplicity and applicability and have served as valuable scientific tools since the 19th century. Linear models continue to serve an important role across science, medicine, mathematics, and statistics. Furthermore, they serve as the backbone to nearly all machine learning and artificial intelligence methods and can be used to generate predictions about relationships between variables. 

This project applies linear regression methods to mortality data from Puerto Rico's Department of Health Demographic Registry between 2002 and 2017 in order to quantify the excess mortality rate following Hurricane Maria and to understand the true humanitarian impact of the storm. We begin by exploring population demographics and trends in sex and age groups in order to thoughtfully inform our modeling and predictions. We next fit a multiple linear model regressing age category, sex, week value and date on observed death rate, with added effect modification between age category and sex and age category and week value. We utilize this model to generate predicted death rates and compare with observed death rates. We discuss our findings in the context of the severe underreporting of true deaths by the Puerto Rico government, and argue that this analysis procedure may serve as a model for future analysis of mortality during severe weather events. 

### Methods

-   \[information about the data\]

-   All visualizations created using ggplot2

-   Wrangling

To assess population sizes by age group and sex, we first began by using ggplot2 to plot a line graph of population across date. Each line was colored by age group to differentiate between age group, and the plot was facet wrapped by sex in order to compare between males and females.

Next, we created two age structure diagrams, one for 2002 and one for 2016 (see Supplementary 1A). We did so by creating two new data frames filtered from weekly_counts by their respective year. Data frames were grouped by agegroup and sex and then the average population for the year was calculated using the summarize() and mean() functions. Finally, these two data frames were plotted using middle centered bar graphs plotted for population by age group. The patchwork package was used to plot both plots next to each other in one figure.

-   2 3 4

-   5

### Results

-   Among both males and females, the youngest population groups have declined dramatically in size since the early 2000s whereas oldest population groups have grown markedly. This can be seen in both the line graph below, which plots population sizes over time stratified by sex and age group, and in Supplementary Figure 1A, which compares population size by sex and age group between 2002 and 2016. The overall population size in Puerto Rico has remained relatively stable from 2002 to 2016.

-   2 3 4

-   5

### Discussion
